In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
from scipy.linalg import hilbert

x = hilbert(10)
x

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
        0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.5       , 0.33333333, 0.25      , 0.2       , 0.16666667,
        0.14285714, 0.125     , 0.11111111, 0.1       , 0.09090909],
       [0.33333333, 0.25      , 0.2       , 0.16666667, 0.14285714,
        0.125     , 0.11111111, 0.1       , 0.09090909, 0.08333333],
       [0.25      , 0.2       , 0.16666667, 0.14285714, 0.125     ,
        0.11111111, 0.1       , 0.09090909, 0.08333333, 0.07692308],
       [0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
        0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ,
        0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667],
       [0.14285714, 0.125     , 0.11111111, 0.1       , 0.09090909,
        0.08333333, 0.07692308, 0.07142857, 0.06666667, 0.0625    ],
       [0.125     , 0.11111111, 0.1      

In [5]:
pd.DataFrame(x, columns=['x'+str(i) for i in range(1,11)]).corr()

x1        x2        x3        x4        x5        x6        x7  \
x1   1.000000  0.985344  0.965392  0.948277  0.934230  0.922665  0.913025   
x2   0.985344  1.000000  0.995632  0.988183  0.980720  0.973927  0.967905   
x3   0.965392  0.995632  1.000000  0.998160  0.994616  0.990719  0.986928   
x4   0.948277  0.988183  0.998160  1.000000  0.999065  0.997120  0.994845   
x5   0.934230  0.980720  0.994616  0.999065  1.000000  0.999465  0.998294   
x6   0.922665  0.973927  0.990719  0.997120  0.999465  1.000000  0.999669   
x7   0.913025  0.967905  0.986928  0.994845  0.998294  0.999669  1.000000   
x8   0.904883  0.962598  0.983393  0.992525  0.996860  0.998914  0.999782   
x9   0.897921  0.957918  0.980155  0.990281  0.995346  0.997959  0.999271   
x10  0.891902  0.953774  0.977207  0.988163  0.993839  0.996922  0.998608   

           x8        x9       x10  
x1   0.904883  0.897921  0.891902  
x2   0.962598  0.957918  0.953774  
x3   0.983393  0.980155  0.977207  
x4   0.992525  0.990281  0.988163  
x5   0.996860  0.995346  0.993839  
x6   0.998914  0.997959  0.996922  
x7   0.999782  0.999271  0.998608  
x8   1.000000  0.999850  0.999491  
x9   0.999850  1.000000  0.999893  
x10  0.999491  0.999893  1.000000

In [19]:
np.random.seed(10)
w = np.random.randint(2, 10, 10) 
y = x @ w

y = np.array(y)

In [20]:
w

array([3, 7, 6, 9, 2, 3, 5, 6, 3, 7])

In [21]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(x, y)

LinearRegression()

In [22]:
model.coef_

array([3.00000109, 6.99989175, 6.00259997, 8.9736951 , 2.13817087,
       2.58531247, 5.73748497, 5.23217956, 3.43201297, 6.89864025])

In [23]:
from sklearn.linear_model import Ridge

ridge_model = Ridge(fit_intercept=False)  # 参数代表不增加截距项
ridge_model.fit(x, y)

Ridge(fit_intercept=False)

In [24]:
ridge_model.coef_

array([6.3497497 , 4.32792068, 3.40228975, 2.83692059, 2.44632895,
       2.15683095, 1.93213214, 1.75189668, 1.60369747, 1.47944808])