In [3]:
import numpy as np

1、导入numpy作为np，并查看版本

In [4]:
np.__version__

'1.25.1'

2. 问题：创建从0到9的一维数字数组

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3. 创建一个numpy数组元素值全为True（真）的数组

In [7]:
np.full((3, 3), True, bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

4. 从 arr 中提取所有的奇数

In [8]:
arr = np.arange(10)
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

5. 将arr中的所有奇数替换为-1

In [10]:
arr = np.arange(10)
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

6. 将arr中的所有奇数替换为-1，而不改变arr

In [12]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

7. 将一维数组转换为2行的2维数组

In [13]:
arr = np.arange(10)
arr.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

8. 垂直堆叠数组a和数组b

In [17]:
# 给定
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

9. 将数组a和数组b水平堆叠

In [19]:
# 给定
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.concatenate([a, b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

10. 创建以下模式而不使用硬编码。只使用numpy函数和下面的输入数组a
```
给定：
a = np.array([1,2,3])
期望的输出：
# > array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [22]:
a = np.array([1,2,3])
np.hstack([np.repeat(a, 3), np.tile(a, 3)])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])